### ISSUE TITLE
Existing secret failure

### ISSUE THREAD

**Issue by kononovbolt** [peimanja/helm-charts#10]
hey)
In helm values if set existingSecret: true, the manifest gets render error.
the template manifest then looks like that:
envFrom:
    - secretRef:
       name: %!s(bool=true)

Error: YAML parse error on prometheus-artifactory-exporter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: found character that cannot start any token

**Comment by tomgeorge** [comment]
What was the resolution for this? I'm running into it as well
