### ISSUE TITLE
Changing tag to canary to support open metrics throws error

### ISSUE THREAD

**Issue by alexbospnw** [peimanja/helm-charts#17]
**Describe the bug**
If i install this helm chart but change the image tag to canary in order to support open metrics I receive the following error and the pod restarts

./artifactory_exporter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./artifactory_exporter)

**Version of Helm and Kubernetes**:

Helm Version:
'''version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}'''

Kubernetes Version:

```console
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-artifactory-exporter

**Which version of the chart**:
1.13.2

**What happened**:

**What you expected to happen**:
the pod starts and runs

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

image:
  registry: ghcr.io
  repository: peimanja/artifactory_exporter
  # set to canary for the latest unreleased version
  tag: canary

artifactory:
  url: artifactoryURL
  accessToken: token  

optionalMetrics:
     - artifacts 
     - replication_status
     - federation_status 
     - open_metrics

**The helm command that you execute and failing/misfunctioning**:

```helm upgrade artifactory-exporter peimanja/prometheus-artifactory-exporter -f values-artifactory-exporter.yaml -n artifactory-devl
```

**Comment by peimanja** [comment]
Thanks for reporting, new version is out and it should fix your issue as well
