### ISSUE TITLE
Pod prometheus-artifactory-exporter created by the helm chart is in CrashLoopBackOff

### ISSUE THREAD

**Issue by SWBSanjeewa** [peimanja/helm-charts#7]
I have updated the values.yml with correct artifactory url, username, password and access_token before installing the helm chart.
When I checked the pod using describe command I could see ARTI_SCRAPE_URI env correctly set and some env variables had been loaded from a secret resource( ARTI_USERNAME,ARTI_PASSWORD )

The logs of the previous pod generated using -p option was
$ kubectl logs chart-1612503482-prometheus-artifactory-exporter-5858cc9f7wn4wc -p
time="2021-02-05T05:38:55Z" level=error msg="Error creating the config. err: `ARTI_USERNAME` and `ARTI_PASSWORD` or `ARTI_ACCESS_TOKEN` environment variable hast to be set" source="artifactory_exporter.go:20"

**Comment by peimanja** [comment]
Please open if you still experiencing any issues
